import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './themes/magazine-green.css';
import './prototype-home.css';

// PROTOTYPE: Three variants of the 开发阿雷 homepage, switchable via ?variant=A|B|C.
const recommended = [
  { type: '深度实践', title: '我用 30 天重做了自己的知识管理系统', tag: '效率工具', color: 'yellow', art: 'nodes', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1300&q=85' },
  { type: '作品复盘', title: '把一个糟糕的需求，变成可交付的产品', tag: '产品开发', color: 'pink', art: 'window', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1300&q=85' },
  { type: '开发笔记', title: '不要再把 README 当作项目的最后一步', tag: '工程化', color: 'blue', art: 'code', image: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1300&q=85' },
  { type: '本周链接', title: '那些让我停下来做笔记的 12 个网站', tag: '书签', color: 'green', art: 'book', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1300&q=85' },
  { type: '投资观察', title: '我如何记录一笔长期投资的判断过程', tag: '个人记录', color: 'orange', art: 'chart', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1300&q=85' },
];
const articles = [
  ['别急着写代码，先让需求变得可以讨论', '从混乱沟通到清晰决策，我常用的一页纸方法。', '产品思考', '8 分钟'],
  ['用更少的工具，完成更深的专注', '我的开发环境、笔记流和每周复盘。', '效率工具', '6 分钟'],
  ['一个人也能做出有温度的产品页面', '从内容层级、留白到不讨好的视觉选择。', '设计实践', '10 分钟'],
  ['给 Side Project 的 5 个完成定义', '别让「差不多了」成为项目永远上线不了的原因。', '独立开发', '5 分钟'],
  ['从 Bug 报告里挖出真正的问题', '技术排障之外，如何识别产品和协作里的假问题。', '工程管理', '7 分钟'],
];
const works = [
  ['写作工作台', '给长文写作者的轻量发布工具', 'React · Markdown', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=85'],
  ['面包店记账', '小生意的日常现金流面板', '产品设计 · 数据', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=85'],
  ['路线图实验室', '让团队讨论不再卡在会议室', '协作 · 原型', 'https://images.unsplash.com/photo-1550439062-609e1531270e?auto=format&fit=crop&w=900&q=85'],
];
const activity = ['08.01  发布《给 Side Project 的 5 个完成定义》', '07.28  完成“写作工作台”首轮测试', '07.24  正在读《设计中的设计》', '07.20  B站更新：我的本地开发流'];
const bookmarks = ['Raycast · 工具箱', 'CSS-Tricks · 前端笔记', 'NOWNESS · 灵感采样', '小众软件 · 数字生活', 'Margin · 独立杂志', 'A List Apart · 设计思考'];

function Artwork({ kind = 'nodes' }) { return <div className={'art ' + kind} aria-hidden="true"><i/><b/>{kind === 'nodes' && <><em/><span/></>}{kind === 'code' && <code>&lt;/&gt;</code>}{kind === 'chart' && <strong>↗</strong>}{kind === 'book' && <strong>✦</strong>}</div> }
function Logo() { return <a href="#top" className="logo" aria-label="开发阿雷首页"><span>开</span><b>发阿雷</b><small>DEV ALEI</small></a> }
function Header({ variant }) { const [open, setOpen] = useState(false); const links = ['首页','文章','关于我','合作','作品','动态','友链','投资','书签']; return <header className={'header header-' + variant}><Logo/><nav className={open ? 'open' : ''} aria-label="主导航">{links.map((x,i) => <a key={x} className={i === 0 ? 'active' : ''} href={i ? '#soon' : '#top'} onClick={i ? e => { e.preventDefault(); document.getElementById('soon').showModal(); } : undefined}>{x}</a>)}</nav><div className="social"><button onClick={() => document.getElementById('soon').showModal()} aria-label="GitHub">GH</button><button onClick={() => document.getElementById('soon').showModal()} aria-label="哔哩哔哩">B</button><button className="menu" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="打开菜单">☰</button></div></header> }
function Hero({ compact = false, editorial = false }) { const [current,setCurrent] = useState(0); const [paused,setPaused] = useState(false); const item = recommended[current]; useEffect(() => { if (paused || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const t = setInterval(() => setCurrent(x => (x + 1) % recommended.length), 5000); return () => clearInterval(t); }, [paused]); const go = (next) => { setPaused(true); setCurrent((next + recommended.length) % recommended.length); }; return <section className={'hero ' + (compact ? 'hero-compact ' : '') + (editorial ? 'hero-editorial' : '')} onMouseEnter={() => setPaused(true)} aria-label="本期推荐"><div className={'hero-main ' + item.color}>{editorial ? <img className="hero-photo" src={item.image} alt=""/> : <Artwork kind={item.art}/>}<div className="hero-copy"><p className="eyebrow">本期推荐 / {item.type}</p><h1>{item.title}</h1><span className="tag">#{item.tag}</span><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>阅读这篇 <b>→</b></button></div><div className="hero-controls"><button onClick={() => go(current - 1)} aria-label="上一条推荐">←</button><b>{String(current + 1).padStart(2,'0')}</b><button onClick={() => go(current + 1)} aria-label="下一条推荐">→</button></div></div><div className="hero-list">{recommended.map((x,i) => <button key={x.title} onClick={() => go(i)} className={i === current ? 'selected' : ''}><span>{String(i + 1).padStart(2,'0')}</span><div><small>{x.type}</small><b>{x.title}</b></div>{i === current && <em>↗</em>}</button>)}</div></section> }
function SectionTitle({ number, title, link = '查看全部' }) { return <div className="section-title"><span>{number}</span><h2>{title}</h2><button onClick={() => document.getElementById('soon').showModal()}>{link} <b>↗</b></button></div> }
function Articles({ mode = 'list' }) { return <section className={'section articles ' + mode}><SectionTitle number="01" title="最新文章"/>
  <div className="article-layout"><div className="article-list">{articles.map((a,i) => <article className="article" key={a[0]}><div className={'article-stamp s' + i}>{String(i+1).padStart(2,'0')}</div><div><p>{a[2]} <i>·</i> 2026.07.{30-i}</p><h3>{a[0]}</h3><p className="muted">{a[1]}</p><small>阅读约 {a[3]} <b>→</b></small></div></article>)}</div><aside className="topic-box"><b>本月主题</b><h3>做个有耐心的创作者。</h3><p>#独立开发 #产品复盘 #效率系统 #慢思考</p><span>☻</span></aside></div></section> }
function Works({ editorial = false }) { return <section className={'section works ' + (editorial ? 'works-editorial' : '')}><SectionTitle number="02" title="精选作品" link="所有作品"/><div className="work-grid">{works.map((w,i) => <article key={w[0]} className={'work w'+i}>{editorial ? <img className="work-photo" src={w[3]} alt=""/> : <Artwork kind={['window','chart','code'][i]}/>}<p>{w[2]}</p><h3>{w[0]}</h3><span>{w[1]}</span><button onClick={() => document.getElementById('soon').showModal()}>查看案例 ↗</button></article>)}</div></section> }
function About() { return <section className="about"><div className="avatar"><span>👨🏻‍💻</span><i>HELLO!</i></div><div><p className="eyebrow">03 / 关于开发阿雷</p><h2>你好，我是开发阿雷。<br/>一个持续练习的产品开发者。</h2><p>我写代码、做产品，也记录那些从模糊到清晰的过程。这里像一本慢慢变厚的独立杂志。</p><div className="stats"><b>6<span>年写作</span></b><b>42<span>篇文章</span></b><b>12<span>个项目</span></b></div></div><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>认识我 →</button></section> }
function LowerSections() { return <><section className="section activity"><SectionTitle number="04" title="最近动态" link="动态归档"/><div className="timeline">{activity.map((x,i) => <div key={x}><i>{i === 0 ? 'NOW' : '·'}</i><p>{x}</p></div>)}</div></section><section className="section investment"><SectionTitle number="05" title="投资观察" link="查看记录"/><div className="investment-card"><div><p className="eyebrow">长期观察 / 2026 Q3</p><h3>不追涨跌，只记录我理解世界的方式。</h3><p>关注：AI 基础设施、消费品牌、创作者经济</p></div><div className="chart-line"><span>↗</span><i/><i/><i/></div></div><small>⚠ 仅为个人记录，不构成投资建议。</small></section><section className="section bookmarks"><SectionTitle number="06" title="我的书签" link="书签库"/><div>{bookmarks.map((x,i) => <button key={x} onClick={() => document.getElementById('soon').showModal()}><b>{String(i+1).padStart(2,'0')}</b>{x}<span>↗</span></button>)}</div></section><section className="friends"><div><p className="eyebrow">07 / 友链</p><h2>在好奇的人群里<br/>继续交换想法。</h2><button onClick={() => document.getElementById('soon').showModal()}>认识朋友 ↗</button></div><div className="collab"><p>有一个值得认真做的想法？</p><h2>那就一起把它做出来。</h2><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>聊聊合作 →</button><span>✳</span></div></section></> }
function Footer(){ return <footer><Logo/><p>把复杂的事，说得有意思一点。</p><div><button onClick={() => document.getElementById('soon').showModal()}>GitHub</button><button onClick={() => document.getElementById('soon').showModal()}>Bilibili</button><button onClick={() => document.getElementById('soon').showModal()}>RSS</button></div><small>© 2026 开发阿雷 · 已运行 365 天</small></footer> }
function VariantA(){ return <main className="variant variant-a"><Hero/><Articles/><Works/><About/><LowerSections/></main> }
function VariantB(){ return <main className="variant variant-b"><div className="manifesto"><p>THE ALEI POST · ISSUE 01</p><h1>写下过程，<br/><i>也做出答案。</i></h1><span>独立开发 / 产品思考 / 长期主义</span></div><Hero compact editorial/><About/><Articles mode="cards"/><Works editorial/><LowerSections/></main> }
function VariantC(){ return <main className="variant variant-c"><div className="bulletin"><span>DEVELOPER'S BULLETIN</span><h1>今天，也做点<br/>有意思的东西。</h1><p>第 31 期 · 2026.08</p></div><div className="c-top"><Hero compact/><div className="quick-note"><b>本周便签</b><p>“把不确定的事，变成下一步能做的事。”</p><span>— Ale i</span></div></div><Works/><Articles mode="cards"/><LowerSections/><About/></main> }
const names={A:'编辑部双栏',B:'独立杂志长卷',C:'公告板网格'};
function Switcher({variant,setVariant}) { if (import.meta.env.PROD) return null; const keys=['A','B','C']; const cycle=(d)=>setVariant(keys[(keys.indexOf(variant)+d+3)%3]); useEffect(()=>{const fn=e=>{const el=document.activeElement; if(['INPUT','TEXTAREA'].includes(el?.tagName)||el?.isContentEditable)return; if(e.key==='ArrowLeft')cycle(-1); if(e.key==='ArrowRight')cycle(1)}; addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[variant]); return <aside className="switcher"><button onClick={()=>cycle(-1)} aria-label="上一种方案">←</button><span><b>{variant}</b> — {names[variant]}</span><button onClick={()=>cycle(1)} aria-label="下一种方案">→</button></aside> }
function App(){ const initial=new URLSearchParams(location.search).get('variant'); const [variant,setState]=useState(['A','B','C'].includes(initial)?initial:'B'); const setVariant=v=>{setState(v);const u=new URL(location);u.searchParams.set('variant',v);history.replaceState({},'',u)}; return <><div id="top" className="page theme-magazine-green"><Header variant={variant}/>{variant==='A'?<VariantA/>:variant==='B'?<VariantB/>:<VariantC/>}<Footer/></div><Switcher variant={variant} setVariant={setVariant}/><dialog id="soon"><button onClick={e=>e.currentTarget.parentElement.close()} aria-label="关闭">×</button><h2>这个栏目正在排版中。</h2><p>首页原型先把内容与体验呈现给你。</p></dialog></> }
createRoot(document.getElementById('root')).render(<App/>);
