import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './themes/magazine-green.css';
import './prototype-home.css';
import './pages.css';
import { MvpPage } from './pages';
import { activity, articles, bookmarks, recommended, works } from './data/home-content';
import { SiteFooter, SiteHeader } from './components/SiteShell';
import { VariantSwitcher } from './components/VariantSwitcher';

// PROTOTYPE: Three variants of the 开发阿雷 homepage, switchable via ?variant=A|B|C.

function Artwork({ kind = 'nodes' }) { return <div className={'art ' + kind} aria-hidden="true"><i/><b/>{kind === 'nodes' && <><em/><span/></>}{kind === 'code' && <code>&lt;/&gt;</code>}{kind === 'chart' && <strong>↗</strong>}{kind === 'book' && <strong>✦</strong>}</div> }
function Hero({ compact = false, layout = 'editorial' }) { const [current,setCurrent] = useState(0); const [paused,setPaused] = useState(false); const item = recommended[current]; useEffect(() => { if (paused || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const t = setInterval(() => setCurrent(x => (x + 1) % recommended.length), 5000); return () => clearInterval(t); }, [paused]); const go = (next) => { setPaused(true); setCurrent((next + recommended.length) % recommended.length); }; return <section className={`hero hero-${layout} ${compact ? 'hero-compact' : ''}`} onMouseEnter={() => setPaused(true)} aria-label="本期推荐"><div className={'hero-main ' + item.color}><img key={item.image} className="hero-photo" src={item.image} alt={`${item.title} 的风景封面`}/><div className="hero-copy"><p className="eyebrow">本期推荐 / {item.type}</p><h1>{item.title}</h1><span className="tag">#{item.tag}</span><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>阅读这篇 <b>→</b></button></div><div className="hero-controls"><button onClick={() => go(current - 1)} aria-label="上一条推荐">←</button><b>{String(current + 1).padStart(2,'0')}</b><button onClick={() => go(current + 1)} aria-label="下一条推荐">→</button></div></div><div className="hero-list">{recommended.map((x,i) => <button key={x.title} onClick={() => go(i)} className={i === current ? 'selected' : ''}><span>{String(i + 1).padStart(2,'0')}</span><div><small>{x.type}</small><b>{x.title}</b></div>{i === current && <em>↗</em>}</button>)}</div></section> }
function SectionTitle({ number, title, link = '查看全部' }) { return <div className="section-title"><span>{number}</span><h2>{title}</h2><button onClick={() => document.getElementById('soon').showModal()}>{link} <b>↗</b></button></div> }
function Articles({ mode = 'list' }) { return <section className={'section articles ' + mode}><SectionTitle number="01" title="最新文章"/>
  <div className="article-layout"><div className="article-list">{articles.map((a,i) => <article className="article" key={a[0]}><div className={'article-stamp s' + i}>{String(i+1).padStart(2,'0')}</div><div><p>{a[2]} <i>·</i> 2026.07.{30-i}</p><h3>{a[0]}</h3><p className="muted">{a[1]}</p><small>阅读约 {a[3]} <b>→</b></small></div></article>)}</div><aside className="topic-box"><b>本月主题</b><h3>做个有耐心的创作者。</h3><p>#独立开发 #产品复盘 #效率系统 #慢思考</p><span>☻</span></aside></div></section> }
function Works({ editorial = false }) { return <section className={'section works ' + (editorial ? 'works-editorial' : '')}><SectionTitle number="02" title="精选作品" link="所有作品"/><div className="work-grid">{works.map((w,i) => <article key={w[0]} className={'work w'+i}>{editorial ? <img className="work-photo" src={w[3]} alt=""/> : <Artwork kind={['window','chart','code'][i]}/>}<p>{w[2]}</p><h3>{w[0]}</h3><span>{w[1]}</span><button onClick={() => document.getElementById('soon').showModal()}>查看案例 ↗</button></article>)}</div></section> }
function About() { return <section className="about"><div className="avatar"><span>👨🏻‍💻</span><i>HELLO!</i></div><div><p className="eyebrow">03 / 关于开发阿雷</p><h2>你好，我是开发阿雷。<br/>一个持续练习的产品开发者。</h2><p>我写代码、做产品，也记录那些从模糊到清晰的过程。这里像一本慢慢变厚的独立杂志。</p><div className="stats"><b>6<span>年写作</span></b><b>42<span>篇文章</span></b><b>12<span>个项目</span></b></div></div><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>认识我 →</button></section> }
function LowerSections() { return <><section className="section activity"><SectionTitle number="04" title="最近动态" link="动态归档"/><div className="timeline">{activity.map((x,i) => <div key={x}><i>{i === 0 ? 'NOW' : '·'}</i><p>{x}</p></div>)}</div></section><section className="section investment"><SectionTitle number="05" title="投资观察" link="查看记录"/><div className="investment-card"><div><p className="eyebrow">长期观察 / 2026 Q3</p><h3>不追涨跌，只记录我理解世界的方式。</h3><p>关注：AI 基础设施、消费品牌、创作者经济</p></div><div className="chart-line"><span>↗</span><i/><i/><i/></div></div><small>⚠ 仅为个人记录，不构成投资建议。</small></section><section className="section bookmarks"><SectionTitle number="06" title="我的书签" link="书签库"/><div>{bookmarks.map((x,i) => <button key={x} onClick={() => document.getElementById('soon').showModal()}><b>{String(i+1).padStart(2,'0')}</b>{x}<span>↗</span></button>)}</div></section><section className="friends"><div><p className="eyebrow">07 / 友链</p><h2>在好奇的人群里<br/>继续交换想法。</h2><button onClick={() => document.getElementById('soon').showModal()}>认识朋友 ↗</button></div><div className="collab"><p>有一个值得认真做的想法？</p><h2>那就一起把它做出来。</h2><button className="ink-button" onClick={() => document.getElementById('soon').showModal()}>聊聊合作 →</button><span>✳</span></div></section></> }
function VariantA(){ return <main className="variant variant-a"><div className="a-kicker"><b>THE ALEI REVIEW</b><span>内容发现 / 每周更新</span></div><Hero layout="editorial"/><Articles/><Works editorial/><About/><LowerSections/></main> }
function VariantB(){ return <main className="variant variant-b"><div className="manifesto"><p>THE ALEI POST · ISSUE 01</p><h1>写下过程，<br/><i>也做出答案。</i></h1><span>独立开发 / 产品思考 / 长期主义</span></div><Hero compact layout="editorial"/><About/><Articles mode="cards"/><Works editorial/><LowerSections/></main> }
function VariantC(){ return <main className="variant variant-c"><div className="bulletin"><span>DEVELOPER'S BULLETIN</span><h1>今天，也做点<br/>有意思的东西。</h1><p>第 31 期 · 2026.08</p></div><div className="c-top"><Hero compact layout="bulletin"/><div className="quick-note"><b>本周便签</b><p>“把不确定的事，变成下一步能做的事。”</p><span>— Ale i</span></div></div><Works editorial/><Articles mode="cards"/><LowerSections/><About/></main> }
function App(){ const params=new URLSearchParams(location.search); const initial=params.get('variant'); const page=params.get('page') || 'home'; const [variant,setState]=useState(['A','B','C'].includes(initial)?initial:'B'); useEffect(()=>{document.body.classList.add('theme-magazine-green');return()=>document.body.classList.remove('theme-magazine-green')},[]); const setVariant=v=>{setState(v);const u=new URL(location);u.searchParams.set('variant',v);history.replaceState({},'',u)}; const isHome=page==='home'; const showNotice=()=>document.getElementById('soon').showModal(); return <><div id="top" className="page theme-magazine-green"><SiteHeader page={page} onExternalClick={showNotice}/>{isHome ? (variant==='A'?<VariantA/>:variant==='B'?<VariantB/>:<VariantC/>) : <MvpPage page={page}/>}<SiteFooter onExternalClick={showNotice}/></div>{isHome && <VariantSwitcher variant={variant} onChange={setVariant}/>}<dialog id="soon"><button onClick={e=>e.currentTarget.parentElement.close()} aria-label="关闭">×</button><h2>这个栏目正在排版中。</h2><p>首页原型先把内容与体验呈现给你。</p></dialog></> }
createRoot(document.getElementById('root')).render(<App/>);
