import { useState } from 'react';

const articleRows = [
  ['产品思考', '别急着写代码，先让需求变得可以讨论', '从混乱沟通到清晰决策，我常用的一页纸方法。', '2026.07.30'],
  ['效率工具', '用更少的工具，完成更深的专注', '我的开发环境、笔记流和每周复盘。', '2026.07.29'],
  ['设计实践', '一个人也能做出有温度的产品页面', '从内容层级、留白到不讨好的视觉选择。', '2026.07.28'],
  ['独立开发', '给 Side Project 的 5 个完成定义', '别让「差不多了」成为项目永远上线不了的原因。', '2026.07.27'],
];
const productCatalog = [
  { name: '写作工作台', summary: '给长文写作者的轻量发布工具', type: '工具', tags: 'React · Markdown', status: '持续维护', date: '2026.07', featured: true, image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=85' },
  { name: '面包店记账', summary: '小生意的日常现金流面板', type: 'Web 产品', tags: '产品设计 · 数据', status: '已发布', date: '2026.05', featured: true, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85' },
  { name: '路线图实验室', summary: '让团队讨论不再卡在会议室', type: '协作工具', tags: '协作 · 原型', status: '持续维护', date: '2026.03', featured: true, image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1000&q=85' },
  { name: '像素邮局', summary: '将订阅邮件变成可阅读的个人刊物', type: '内容产品', tags: '内容 · 邮件', status: '已发布', date: '2025.12', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85' },
  { name: '专注计时器', summary: '为深度工作设计的极简浏览器工具', type: '工具', tags: 'Web · Chrome', status: '已归档', date: '2025.08', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85' },
  { name: '城市散步', summary: '记录城市路线与街头发现的小应用', type: '实验项目', tags: '地图 · 日记', status: '实验中', date: '2025.04', image: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=900&q=85' },
  { name: '空白画布', summary: '帮助团队同步想法的轻量白板', type: 'Web 产品', tags: '协作 · Canvas', status: '实验中', date: '2024.11', image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=85' },
  { name: '开源清单', summary: '值得信赖的小型开源工具收藏', type: '开源项目', tags: '社区 · Curated', status: '持续维护', date: '2024.06', image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=85' },
];
const copy = {
  articles: ['文章', '把做过、想过、踩过的坑，写成可以被带走的东西。'],
  about: ['关于我', '一个持续练习的产品开发者，也是一名过程记录者。'],
  collaboration: ['合作', '从模糊想法到可用产品，一起把值得做的事做出来。'],
  works: ['作品', '一些从问题出发、被认真做完的产品实验。'],
  activity: ['动态', '创作、阅读、学习与开发，正在发生的事情。'],
  friends: ['友链', '在好奇的人群里，继续交换想法。'],
  investment: ['投资', '不追涨跌，只记录我理解世界的方式。'],
  bookmarks: ['书签', '留给那些值得再次打开的网站、工具与文章。'],
};

function Masthead({ page }) { const [title, intro] = copy[page]; return <section className="page-masthead"><p>DEVELOPER ALEI / {String(Object.keys(copy).indexOf(page) + 1).padStart(2, '0')}</p><div><h1>{title}</h1><span>{intro}</span></div></section> }
const Dot = () => <span className="brutal-dot" aria-hidden="true">✦</span>;

function ArticlesPage() { const [category, setCategory] = useState('全部'); const [view, setView] = useState('list'); const [query, setQuery] = useState(''); const categories = ['全部', ...new Set(articleRows.map(row => row[0]))]; const visible = articleRows.filter(row => (category === '全部' || row[0] === category) && `${row[1]}${row[2]}`.toLowerCase().includes(query.toLowerCase())); return <section className={`page-section article-index ${view}`}><div className="article-toolbar"><nav aria-label="文章分类">{categories.map(item => <button className={category === item ? 'selected' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</nav><div><label><span className="sr-only">搜索文章</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索文章…"/></label><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')} aria-label="列表视图">☷</button><button className={view === 'cards' ? 'selected' : ''} onClick={() => setView('cards')} aria-label="卡片视图">▦</button></div></div><p className="article-count">{category} · 找到 {visible.length} 篇文章</p><div className="article-listing">{visible.map((row, index) => <article key={row[1]}><i>{String(index + 1).padStart(2, '0')}</i><div><small>{row[0]} · {row[3]}</small><h2>{row[1]}</h2><p>{row[2]}</p></div><b>↗</b></article>)}</div></section> }
function SampleQr() { return <svg className="sample-qr" viewBox="0 0 116 116" role="img" aria-label="示例二维码，仅用于页面展示"><rect width="116" height="116" fill="currentColor" opacity=".08"/><g fill="currentColor"><path d="M8 8h31v31H8zm6 6v19h19V14zM77 8h31v31H77zm6 6v19h19V14zM8 77h31v31H8zm6 6v19h19V83zM48 9h7v7h-7zm14 0h8v8h-8zm-14 15h14v7H48zm15 9h8v8h-8zm-15 15h8v8h-8zm15 0h7v15h-7zm15 0h8v8h-8zm16 0h9v9h-9zM48 63h8v8h-8zm15 0h8v8h-8zm15 0h15v7H78zm-30 15h8v8h-8zm15 0h8v15h-8zm15 0h8v8h-8zm16 15h14v8H94zM48 94h8v14h-8zm15 0h16v8H63z"/></g></svg> }
function AboutPage() {
  const channels = [['合作微信号', '微信名片', '添加中', '用于项目合作与技术咨询'], ['交流 QQ 群', '社群交流', '即将开放', '和正在做产品的人交换经验'], ['抖音', '短视频', '开发阿雷', '技术变化里的个人实践'], ['哔哩哔哩', '视频频道', '开发阿雷', '把开发过程讲得更明白'], ['小红书', '图文记录', '开发阿雷', '工具、创作与工作流'], ['微信公众号', '深度文章', '开发阿雷', '值得慢慢读完的技术故事']];
  return <section className="page-section about-page about-profile">
    <div className="about-intro"><div className="about-portrait"><span>👨🏻‍💻</span><i>HELLO!</i></div><div className="about-statement"><p className="label">DEVELOPER / WRITER / MAKER</p><h2>把复杂技术讲清楚，<br/>把好用工具做出来。</h2><p className="about-lead">从技术变化到个人实践，写给不想被术语挡住的人。</p><p>我在产品、设计与开发之间来回切换；这里记录可复用的方法，也保留尚未有答案的问题。</p><div className="number-row"><b>6<small>年写作</small></b><b>42<small>篇文章</small></b><b>12<small>个项目</small></b></div></div><aside className="about-now"><b>现在正在</b><p>整理一套给独立开发者用的写作工作台。</p><Dot/></aside></div>
    <div className="about-services"><div><p className="label">TECHNICAL SERVICES / 01</p><h2>有要落地的技术想法？</h2><p>从需求梳理、原型验证到前端实现，把值得做的事情更快推到下一步。</p></div><a href="https://shop.qqphp.com" target="_blank" rel="noreferrer"><span>技术服务商店</span><b>去看看 →</b><small>shop.qqphp.com</small></a></div>
    <section className="about-channels"><div className="about-section-heading"><p className="label">FIND ME / 02</p><h2>在不同的地方，继续交流。</h2></div><div className="channel-grid">{channels.map(([name, type, account, description], index) => <article key={name}><b>{String(index + 1).padStart(2, '0')}</b><small>{type}</small><h3>{name}</h3><div className="channel-card-body"><div><strong>{account}</strong><p>{description}</p></div><SampleQr/></div></article>)}</div></section>
    <div className="about-explore"><p className="label">START HERE / 03</p><h2>不需要搜索。选一个此刻最关心的方向，慢慢往里走。</h2><div>{[['技术与工具', '把工具真正用进工作流。'], ['产品与实践', '从一个问题走到可用的答案。'], ['独立开发', '给长期项目留出完成的空间。']].map(([title, text]) => <button key={title}><b>{title}</b><span>{text}</span><i>↘</i></button>)}</div></div>
    <div className="about-principles"><article><p className="label">WRITING PRINCIPLE / 04</p><h2>先说解决了什么问题，<br/>再聊技术、取舍和走过的弯路。</h2></article><article><p className="label">WHAT STAYS / 05</p><h2>不追热点的每一次浪潮，<br/>只分享值得留下的东西。</h2></article></div>
  </section>
}
function CollaborationPage() { const services = [['01', '产品梳理', '把模糊需求变成可以讨论的方向。'], ['02', '原型与界面', '用可点击的界面提早验证关键判断。'], ['03', '前端实现', '把视觉与交互落地为稳定、清晰的页面。']]; return <section className="page-section collaboration-page"><div className="service-grid">{services.map(x => <article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p><span>→</span></article>)}</div><div className="process"><p className="label">合作流程</p><h2>先一起把问题说清楚。</h2><ol><li>认识问题与目标</li><li>确定最小可行方案</li><li>短周期交付与复盘</li></ol><button>发起一场交流 ↗</button></div></section> }
function WorksPage() { const [type, setType] = useState('全部'); const [sort, setSort] = useState('精选优先'); const [query, setQuery] = useState(''); const types = ['全部', ...new Set(productCatalog.map(item => item.type))]; const sorted = productCatalog.filter(item => (type === '全部' || item.type === type) && `${item.name}${item.summary}${item.tags}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === '精选优先' ? Number(b.featured) - Number(a.featured) || b.date.localeCompare(a.date) : sort === '最新发布' ? b.date.localeCompare(a.date) : a.status.localeCompare(b.status)); const featured = productCatalog.filter(item => item.featured); return <section className="page-section product-library"><section className="all-products"><div className="library-heading"><p className="label">PRODUCT LIBRARY / 01</p><h2>全部产品</h2><span>从全部实践中，慢慢找到你感兴趣的方向。</span></div><div className="product-toolbar"><nav aria-label="产品类型">{types.map(item => <button className={type === item ? 'selected' : ''} onClick={() => setType(item)} key={item}>{item}</button>)}</nav><div><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索产品…" aria-label="搜索产品"/><select value={sort} onChange={event => setSort(event.target.value)} aria-label="排序"><option>精选优先</option><option>最新发布</option><option>项目状态</option></select></div></div><p className="product-count">共 {sorted.length} 个产品</p><div className="product-grid">{sorted.map(item => <article key={item.name}><img src={item.image} alt=""/><div><small>{item.type} · {item.status}</small><h3>{item.name}</h3><p>{item.summary}</p><span>{item.tags}</span><button>查看案例 ↗</button></div></article>)}</div></section><aside className="featured-products"><div className="library-heading"><p className="label">EDITOR’S PICK / 02</p><h2>精选作品</h2><span>三项代表作，作为快速入口。</span></div><div>{featured.map((item, index) => <article key={item.name} className={index === 0 ? 'lead' : ''}><img src={item.image} alt=""/><div><small>{item.type} · {item.status}</small><h3>{item.name}</h3><p>{item.summary}</p><button>查看案例 ↗</button></div></article>)}</div></aside></section> }
function ActivityPage() { const entries = [['08.01', '发布新文章', '给 Side Project 的 5 个完成定义'], ['07.28', '作品进度', '写作工作台完成首轮测试'], ['07.24', '近期阅读', '正在读《设计中的设计》'], ['07.20', '视频更新', 'B站：我的本地开发流']]; return <section className="page-section activity-page">{entries.map((x, i) => <article key={x[0]}><time>{x[0]}</time><i>{i === 0 ? 'NOW' : '·'}</i><div><small>{x[1]}</small><h2>{x[2]}</h2></div></article>)}</section> }
function FriendsPage() { const [view, setView] = useState('cards'); const people = [['少数派', '数字生活与高质量内容', '内容'], ['设计小报', '关于视觉与产品的周刊', '设计'], ['独立开发者', '一群正在做产品的人', '开发'], ['慢慢做', '创作、工具与长期主义', '创作'], ['今日热榜', '把值得关注的信息整理成一页', '资讯'], ['Maybe', '独立杂志与城市文化采样', '灵感'], ['前端食堂', '写给前端人的工程实践', '技术'], ['设计之外', '设计师的生活与工作观察', '设计']]; return <section className={'page-section friends-page ' + view}><div className="friends-toolbar"><p>这些是我经常打开、也愿意推荐给你的站点。<b>{people.length} 位朋友</b></p><div role="group" aria-label="友链展示方式"><button className={view === 'cards' ? 'selected' : ''} onClick={() => setView('cards')}>▦ 卡片</button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}>☷ 列表</button></div></div><div className="friend-collection">{people.map((x, i) => <article key={x[0]}><span>{x[0].slice(0,1)}</span><div><small>{x[2]}</small><h2>{x[0]}</h2><p>{x[1]}</p></div><button aria-label={`访问 ${x[0]}`}>↗</button></article>)}</div><aside>想交换链接？<button>来打个招呼 →</button></aside></section> }
function InvestmentPage() { return <section className="page-section investment-page"><div className="notice">⚠ 仅为个人记录，不构成投资建议。</div><div className="watch-grid"><article><small>长期关注</small><h2>AI 基础设施</h2><p>工具是否真的让人更有创造力。</p></article><article><small>长期关注</small><h2>消费品牌</h2><p>品牌如何在长期里建立信任。</p></article><article><small>长期关注</small><h2>创作者经济</h2><p>个体如何拥有更稳定的收入结构。</p></article></div><div className="investment-note"><p className="label">我的记录原则</p><h2>不预测价格，<br/>只持续更新自己的理解。</h2><span>↗</span></div></section> }
function BookmarksPage() { const groups = [{ name: '开发工具', items: ['Raycast', 'Linear', 'Vercel', 'Warp', 'Figma', 'Obsidian'] }, { name: '设计灵感', items: ['NOWNESS', 'A List Apart', 'It’s Nice That', 'The Brand Identity'] }, { name: '阅读与写作', items: ['Margin', '少数派', 'The Browser'] }, { name: '独立站点', items: ['Read.cv', 'Are.na', 'The Creative Independent', 'Dense Discovery', 'Sidebar'] }]; const density = count => count >= 6 ? 'dense' : count >= 4 ? 'medium' : 'light'; return <section className="page-section bookmark-page">{groups.map((group, i) => <article className={`bookmark-group ${density(group.items.length)}`} key={group.name}><div><b>{String(i + 1).padStart(2, '0')}</b><h2>{group.name}</h2><span>{group.items.length} 条收藏</span></div><section>{group.items.map(name => <button key={name}>{name}<span>↗</span></button>)}</section></article>)}</section> }

export function MvpPage({ page }) { return <main className="mvp-page"><Masthead page={page}/>{page === 'articles' && <ArticlesPage/>}{page === 'about' && <AboutPage/>}{page === 'collaboration' && <CollaborationPage/>}{page === 'works' && <WorksPage/>}{page === 'activity' && <ActivityPage/>}{page === 'friends' && <FriendsPage/>}{page === 'investment' && <InvestmentPage/>}{page === 'bookmarks' && <BookmarksPage/>}</main> }
